## Analyzing Numerical Variables from the Ames Housing Datase
In this exercise, we will continue our dataset exploration by analyzing the numerical variables of this dataset. To do so, we will implement our own describe functions.

In [1]:
import pandas as pd

In [2]:
file_url = ('https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter10/dataset/ames_iowa_housing.csv')

In [3]:
df = pd.read_csv(file_url)
df.shape

(1460, 81)

In [5]:
num_df = df.select_dtypes(include='number')
num_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   OverallQual    1460 non-null   int64
 5   OverallCond    1460 non-null   int64
 6   YearBuilt      1460 non-null   int64
 7   YearRemodAdd   1460 non-null   int64
 8   MasVnrArea     1452 non-null   float64
 9   BsmtFinSF1     1460 non-null   int64
 10  BsmtFinSF2     1460 non-null   int64
 11  BsmtUnfSF      1460 non-null   int64
 12  TotalBsmtSF    1460 non-null   int64
 13  1stFlrSF       1460 non-null   int64
 14  2ndFlrSF       1460 non-null   int64
 15  LowQualFinSF   1460 non-null   int64
 16  GrLivArea      1460 non-null   int64
 17  BsmtFullBath   1460 non-null   int64
 18  BsmtHalfBath   1460 non-null   int64
 19  FullBath       1460 non-null   int64
 20  HalfBath       1460 non-null   int64
 21  BedroomAbvGr   1460 non-null   int64
 22  KitchenAbvGr   1460 non-null   int64
 23  TotRmsAbvGrd   1460 non-null   int64
 24  Fireplaces     1460 non-null   int64
 25  GarageYrBlt    1379 non-null   float64
 26  GarageCars     1460 non-null   int64
 27  GarageArea     1460 non-null   int64
 28  WoodDeckSF     1460 non-null   int64
 29  OpenPorchSF    1460 non-null   int64
 30  EnclosedPorch  1460 non-null   int64
 31  3SsnPorch      1460 non-null   int64
 32  ScreenPorch    1460 non-null   int64
 33  PoolArea       1460 non-null   int64
 34  MiscVal        1460 non-null   int64
 35  MoSold         1460 non-null   int64
 36  YrSold         1460 non-null   int64
 37  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35)
memory usage: 433.6 KB

In [6]:
num_cols = num_df.columns
num_cols

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [9]:
# create describe function
def describe_numeric(df, col_name):
    print('\nCOLUMN: {}'.format(col_name))
    print('Minimun: {}'.format(df[col_name].min()))
    print('Maxmimum: {}'.format(df[col_name].max()))
    print('Average: {}'.format(df[col_name].mean()))
    print('Standard Deviation: {}'.format(df[col_name].std()))
    print('Median: {}'.format(df[col_name].median()))

In [10]:
# create for loop and call describe_numeric function for each column in num_df
for col_name in num_df:
    describe_numeric(num_df, col_name)

COLUMN: Id
Minimun: 1
Maxmimum: 1460
Average: 730.5
Standard Deviation: 421.6100093688479
Median: 730.5

COLUMN: MSSubClass
Minimun: 20
Maxmimum: 190
Average: 56.897260273972606
Standard Deviation: 42.30057099381035
Median: 50.0

COLUMN: LotFrontage
Minimun: 21.0
Maxmimum: 313.0
Average: 70.04995836802665
Standard Deviation: 24.284751774483183
Median: 69.0

COLUMN: LotArea
Minimun: 1300
Maxmimum: 215245
Average: 10516.828082191782
Standard Deviation: 9981.264932379147
Median: 9478.5

COLUMN: OverallQual
Minimun: 1
Maxmimum: 10
Average: 6.0993150684931505
Standard Deviation: 1.3829965467415923
Median: 6.0

COLUMN: OverallCond
Minimun: 1
Maxmimum: 9
Average: 5.575342465753424
Standard Deviation: 1.1127993367127367
Median: 5.0

COLUMN: YearBuilt
Minimun: 1872
Maxmimum: 2010
Average: 1971.267808219178
Standard Deviation: 30.202904042525265
Median: 1973.0

COLUMN: YearRemodAdd
Minimun: 1950
Maxmimum: 2010
Average: 1984.8657534246574
Standard Deviation: 20.645406807709396
Median: 1994.0

COLUMN: MasVnrArea
Minimun: 0.0
Maxmimum: 1600.0
Average: 103.68526170798899
Standard Deviation: 181.06620658721818
Median: 0.0

COLUMN: BsmtFinSF1
Minimun: 0
Maxmimum: 5644
Average: 443.6397260273973
Standard Deviation: 456.09809084092456
Median: 383.5

COLUMN: BsmtFinSF2
Minimun: 0
Maxmimum: 1474
Average: 46.54931506849315
Standard Deviation: 161.31927280654057
Median: 0.0

COLUMN: BsmtUnfSF
Minimun: 0
Maxmimum: 2336
Average: 567.2404109589041
Standard Deviation: 441.8669552924342
Median: 477.5

COLUMN: TotalBsmtSF
Minimun: 0
Maxmimum: 6110
Average: 1057.4294520547944
Standard Deviation: 438.7053244594705
Median: 991.5

COLUMN: 1stFlrSF
Minimun: 334
Maxmimum: 4692
Average: 1162.626712328767
Standard Deviation: 386.5877380410738
Median: 1087.0

COLUMN: 2ndFlrSF
Minimun: 0
Maxmimum: 2065
Average: 346.99246575342465
Standard Deviation: 436.5284358862591
Median: 0.0

COLUMN: LowQualFinSF
Minimun: 0
Maxmimum: 572
Average: 5.844520547945206
Standard Deviation: 48.623081433519125
Median: 0.0

COLUMN: GrLivArea
Minimun: 334
Maxmimum: 5642
Average: 1515.463698630137
Standard Deviation: 525.4803834232027
Median: 1464.0

COLUMN: BsmtFullBath
Minimun: 0
Maxmimum: 3
Average: 0.42534246575342466
Standard Deviation: 0.5189106060897992
Median: 0.0

COLUMN: BsmtHalfBath
Minimun: 0
Maxmimum: 2
Average: 0.057534246575342465
Standard Deviation: 0.23875264627920764
Median: 0.0

COLUMN: FullBath
Minimun: 0
Maxmimum: 3
Average: 1.5650684931506849
Standard Deviation: 0.5509158012954318
Median: 2.0

COLUMN: HalfBath
Minimun: 0
Maxmimum: 2
Average: 0.38287671232876713
Standard Deviation: 0.5028853810928973
Median: 0.0

COLUMN: BedroomAbvGr
Minimun: 0
Maxmimum: 8
Average: 2.8664383561643834
Standard Deviation: 0.8157780441442212
Median: 3.0

COLUMN: KitchenAbvGr
Minimun: 0
Maxmimum: 3
Average: 1.0465753424657533
Standard Deviation: 0.22033819838402977
Median: 1.0

COLUMN: TotRmsAbvGrd
Minimun: 2
Maxmimum: 14
Average: 6.517808219178082
Standard Deviation: 1.625393290584064
Median: 6.0

COLUMN: Fireplaces
Minimun: 0
Maxmimum: 3
Average: 0.613013698630137
Standard Deviation: 0.6446663863122344
Median: 1.0

COLUMN: GarageYrBlt
Minimun: 1900.0
Maxmimum: 2010.0
Average: 1978.5061638868744
Standard Deviation: 24.689724768590214
Median: 1980.0

COLUMN: GarageCars
Minimun: 0
Maxmimum: 4
Average: 1.7671232876712328
Standard Deviation: 0.7473150101111116
Median: 2.0

COLUMN: GarageArea
Minimun: 0
Maxmimum: 1418
Average: 472.9801369863014
Standard Deviation: 213.80484145338076
Median: 480.0

COLUMN: WoodDeckSF
Minimun: 0
Maxmimum: 857
Average: 94.2445205479452
Standard Deviation: 125.33879435172359
Median: 0.0

COLUMN: OpenPorchSF
Minimun: 0
Maxmimum: 547
Average: 46.66027397260274
Standard Deviation: 66.25602767664974
Median: 25.0

COLUMN: EnclosedPorch
Minimun: 0
Maxmimum: 552
Average: 21.954109589041096
Standard Deviation: 61.11914860172879
Median: 0.0

COLUMN: 3SsnPorch
Minimun: 0
Maxmimum: 508
Average: 3.4095890410958902
Standard Deviation: 29.317330556782203
Median: 0.0

COLUMN: ScreenPorch
Minimun: 0
Maxmimum: 480
Average: 15.060958904109588
Standard Deviation: 55.757415281874486
Median: 0.0

COLUMN: PoolArea
Minimun: 0
Maxmimum: 738
Average: 2.758904109589041
Standard Deviation: 40.17730694453043
Median: 0.0

COLUMN: MiscVal
Minimun: 0
Maxmimum: 15500
Average: 43.489041095890414
Standard Deviation: 496.1230244579311
Median: 0.0

COLUMN: MoSold
Minimun: 1
Maxmimum: 12
Average: 6.321917808219178
Standard Deviation: 2.7036262083595197
Median: 6.0

COLUMN: YrSold
Minimun: 2006
Maxmimum: 2010
Average: 2007.8157534246575
Standard Deviation: 1.328095120552104
Median: 2008.0

COLUMN: SalePrice
Minimun: 34900
Maxmimum: 755000
Average: 180921.19589041095
Standard Deviation: 79442.50288288663
Median: 163000.0

In [12]:
describe_numeric(num_df, 'SalePrice')

COLUMN: SalePrice
Minimun: 34900
Maxmimum: 755000
Average: 180921.19589041095
Standard Deviation: 79442.50288288663
Median: 163000.0

In [13]:
num_df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000